### PR TITLE
feat(resumeupload): Added previous record indication

### PR DESCRIPTION
**Pull request by NickBurnett**
Additionally made the upload extension willie-compliant.

### CODE REVIEW

**Review by harshasrikara — APPROVED** [review]

**Comment by NickBurnett** [comment]
@WillieCubed please DM me the vercel logs. I believe this to be a secrets issue.

**Comment by stevenmqnguyen** [comment]
Enforce file size limit?

**Review by stevenmqnguyen — APPROVED** [review]

**Pull request merged**
