### PR TITLE
Improve application styles

### LINKED ISSUE #57: [Feature Request] Make minor updates to Portal styles
# Overview
While Portal v2 is under construction, some styles need to be updated before ACM's spring 2022 kick-off.

# Tasks
- [ ] Change title/heading fonts to Poppins and body fonts to Roboto
- [x] Make applications on the /applications page only occupy a single column on mobile
- [x] Change the old ACM logo to the new ACM logo found in the [ACM Brand Kit](https://github.com/acmutd/brand-kit)
- [x] Change any `onClick` listeners to be standard anchor elements `href` attributes when possible. 
- [ ] Make the sidebar on the profile page occupy less space on mobile devices, ideally being hidden into a menu or tab bar.

### PR DESCRIPTION
**Pull request by WillieCubed**
Closes #57
The biggest changes include:

- Making the applications page take up less space on mobile views
- Using the new ACM logos
- Slightly improving [a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility) by using anchor tags instead of JavaScript when appropriate

### CODE REVIEW

**Review by Balstun — APPROVED** [review]
All changes to formatting and functionally appear functional. Will look into any further adjustments to Portal style.

**Review by stevenmqnguyen — APPROVED** [review]

**Review by Balstun — APPROVED** [review]
I've already approved these changes previously, though I suggest checking why **the checks are failing**. The code is functional locally.

**Pull request merged**
